version: "3.8"

services:
  securityauthenticationinmemory:
    image: samanalishiri/securityauthenticationinmemory:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: securityauthenticationinmemory
    hostname: securityauthenticationinmemory
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
