spring:
  data:
    mongodb:
      username: ${MONGO_DB_USER:root}
      password: ${MONGO_DB_PASS:root}
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:springboot_tutorial}
      authentication-database: admin
      uri: mongodb://${MONGO_DB_USER:root}:${MONGO_DB_PASS:root}@${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_NAME:springboot_tutorial}

