version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318"   # OTLP HTTP
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:16686"]
      interval: 5s
      timeout: 3s
      retries: 20
