server:
  address: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
spring:
  main:
    banner-mode: OFF
  profiles:
    active: ${APP_PROFILES:h2,openapijwt}

secure-resource:
  unsecure-urls:
    - /login
    - /swagger-ui/**
    - /v3/api-docs/**
  home-url: /api/v1/token/me/new
  cors-origin-urls:
    - http://localhost:*
  cors-http-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    - OPTIONS
  cors-http-headers:
    - Authorization
    - Content-Type
  base-path: /**


