server:
  port: 8080
  address: auth-server.local

spring:
  profiles:
    active: h2
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server.local:8080
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server.local:8080/oauth2/jwks
          issuer-uri: http://auth-server.local:8080

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem


