server:
  port: 9000
  address: localhost

logging:
  level:
    web: debug
    org:
      springframework:
        security: debug

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem
