spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      region:
        static: ${AWS_DEFAULT_REGION:us-east-1}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
app:
  queue:
    name: ${APP_QUEUE_NAME:example-queue}