
mvn -f hello-world/pom.xml clean compile verify
mvn -f profile/pom.xml clean compile verify
mvn -f properties/pom.xml clean compile verify
mvn -f logger-log4j2-console/pom.xml clean compile verify
mvn -f logger-log4j2-file/pom.xml clean compile verify
mvn -f logger-log4j2-database/pom.xml clean compile verify
mvn -f event-handling/pom.xml clean compile verify
mvn -f rdbms-h2/pom.xml clean compile verify
mvn -f rdbms-mysql/pom.xml clean compile verify
mvn -f rdbms-postgresql/pom.xml clean compile verify
#mvn -f rdbms-oracle/pom.xml clean compile verify
mvn -f nosql-redis/pom.xml clean compile verify
mvn -f nosql-redis-reactive/pom.xml clean compile verify
mvn -f nosql-mongodb/pom.xml clean compile verify
mvn -f nosql-mongodb-reactive/pom.xml clean compile verify
mvn -f newsql-cockroachdb/pom.xml clean compile verify
mvn -f messaging-apache-artemis-mq/pom.xml clean compile verify
mvn -f messaging-rabbit-mq/pom.xml clean compile verify
mvn -f messaging-apache-kafka/pom.xml clean compile verify
mvn -f messaging-pulsar/pom.xml clean compile verify
mvn -f messaging-redis/pom.xml clean compile verify
mvn -f streaming-apache-kafka/pom.xml clean compile verify
mvn -f cdc-debezium/pom.xml clean compile verify
mvn -f cdc-embedded-debezium/pom.xml clean compile verify
mvn -f log-aggregation-elk/pom.xml clean compile verify
mvn -f observability-grafana-stack/pom.xml clean compile verify
mvn -f observability-jaeger/pom.xml clean compile verify
mvn -f restful-web-api/pom.xml clean compile verify
mvn -f security-rbac-inmemory/pom.xml clean compile verify
mvn -f security-rbac-jwt/pom.xml clean compile verify
mvn -f cloud-aws-s3/pom.xml clean compile verify
mvn -f cloud-aws-sqs/pom.xml clean compile verify