mvn -f hello-world/pom.xml clean
mvn -f profile/pom.xml clean
mvn -f properties/pom.xml clean
mvn -f logger-log4j2-console/pom.xml clean
mvn -f logger-log4j2-file/pom.xml clean
mvn -f logger-log4j2-database/pom.xml clean
mvn -f event-handling/pom.xml clean
mvn -f rdbms-h2/pom.xml clean
mvn -f rdbms-mysql/pom.xml clean
mvn -f rdbms-postgresql/pom.xml clean
mvn -f rdbms-oracle/pom.xml clean
mvn -f nosql-redis/pom.xml clean
mvn -f nosql-redis-reactive/pom.xml clean
mvn -f nosql-mongodb/pom.xml clean
mvn -f nosql-mongodb-reactive/pom.xml clean
mvn -f messaging-apache-artemis-mq/pom.xml clean
mvn -f messaging-rabbit-mq/pom.xml clean
mvn -f messaging-apache-kafka/pom.xml clean
mvn -f messaging-redis/pom.xml clean
mvn -f messaging-pulsar/pom.xml clean
mvn -f streaming-apache-kafka/pom.xml clean
mvn -f streaming-redis/pom.xml clean
mvn -f cdc-debezium/pom.xml clean
mvn -f cdc-embedded-debezium/pom.xml clean
mvn -f log-aggregation-elk/pom.xml clean
mvn -f observability-grafana-stack/pom.xml clean
mvn -f observability-jaeger/pom.xml clean
mvn -f security-rbac-inmemory/pom.xml clean
mvn -f security-rbac-jwt/pom.xml clean