mvn -f hello-world/pom.xml clean
mvn -f profile/pom.xml clean
mvn -f properties/pom.xml clean
mvn -f event-processor/pom.xml clean
mvn -f rdbms-h2/pom.xml clean
mvn -f rdbms-mysql/pom.xml clean
mvn -f rdbms-postgresql/pom.xml clean
mvn -f rdbms-oracle/pom.xml clean
mvn -f nosql-redis/pom.xml clean
mvn -f nosql-redis-reactive/pom.xml clean
mvn -f nosql-mongodb/pom.xml clean
mvn -f nosql-mongodb-reactive/pom.xml clean
mvn -f messaging-apache-artemis-mq/pom.xml clean
mvn -f messaging-rabbit-mq/pom.xml clean
mvn -f messaging-kafka/pom.xml clean
