
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-credentials
  labels:
    app: logstash
type: Opaque
data:
  # logstash_system
  ELASTICSEARCH_USERNAME: bG9nc3Rhc2hfc3lzdGVt
  # password
  ELASTICSEARCH_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }
    
    output {
      stdout {
        codec => rubydebug
      }    
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "logstash_system"
        password => "password"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.10.2
          ports:
            - containerPort: 5044
            - containerPort: 9600
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: ELASTICSEARCH_PASSWORD
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          readinessProbe:
            tcpSocket:
              port: 5044
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - name: defaultbeat
      port: 5044
      targetPort: 5044
    - name: webapi
      port: 9600
      targetPort: 9600
  selector:
    app: logstash