apiVersion: apps/v1
kind: Deployment
metadata:
  name: securityauthenticationinmemory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securityauthenticationinmemory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: securityauthenticationinmemory
    spec:
      containers:
        - name: securityauthenticationinmemory
          image: samanalishiri/securityauthenticationinmemory:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8080"
