apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-credentials
  namespace: dev
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev
data:
  # Zookeeper configs
  ALLOW_ANONYMOUS_LOGIN: "yes"
  # Kafka configs
  KAFKA_CFG_BROKER_ID: "1"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_CFG_LISTENERS: "LOCALHOST://:9092,CONTAINER://:9093"
  KAFKA_CFG_ADVERTISED_LISTENERS: "LOCALHOST://localhost:9092,CONTAINER://kafka-service:9093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "LOCALHOST:PLAINTEXT,CONTAINER:PLAINTEXT"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "LOCALHOST"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  # Kafdrop configs
  KAFKA_BROKERCONNECT: "kafka-service:9093"
  JVM_OPTS: "-Xms32M -Xmx64M"
  # Application configs
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  APP_PROFILES: "kafka"
  KAFKA_URL: "kafka-service:9093"
  KAFKA_GROUP_ID: "main-group"
  KAFKA_TOPIC_NAME: "main-topic"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9.0
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: dev-config
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami
      volumes:
        - name: zookeeper-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: dev
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.9.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          envFrom:
            - configMapRef:
                name: dev-config
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
            - name: config
              mountPath: /config
      volumes:
        - name: kafka-data
          emptyDir: { }
        - name: config
          configMap:
            name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: dev
spec:
  selector:
    app: kafka
  ports:
    - name: localhost
      port: 9092
      targetPort: 9092
    - name: container
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
  namespace: dev
spec:
  selector:
    app: kafdrop
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: samanalishiri/application:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: dev
spec:
  selector:
    app: application
  ports:
    - port: 8080
      targetPort: 8080
