server:
  port: 9000
  address: client-app.local

spring:
  profiles:
    active: h2

logging:
  level:
    org:
      springframework:
        security:
          oauth2:
            client: debug
            core: debug