server:
  port: 9000
  address: client-app.local

spring:
  profiles:
    active: h2

local:
  oauth2:
    server-url: http://auth-server.local:8080
    app-url: http://${server.address}:${server.port}