spring:
  data:
    mongodb:
      username: root
      password: root
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:springboot_tutorial}
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: test
