# Broker URL for embedded Apache Active MQ Artemis is one of the followings.
# localhost:61616
# vm://embeddedartemis
spring:
  artemis:
    mode: embedded
    embedded:
      enabled: true
    broker-url: localhost:6161

# defined by user
queue:
  main: mainQueue
  status: statusQueue
