spring:
  artemis:
    mode: native
    user: ${ACTIVE_MQ_USER:artemis}
    password: ${ACTIVE_MQ_PASS:artemis}
    broker-url: ${ACTIVE_MQ_HOST:localhost}:${ACTIVE_MQ_PORT:61616}
  jms:
    pub-sub-domain: true

# defined by user
queue:
  main: mainQueue
  status: statusQueue

---
spring:
  config:
    activate:
      on-profile: embedded-artemis
  artemis:
    mode: embedded
    embedded:
      enabled: true
    # localhost:61616
    broker-url: vm://embeddedartemis

---
spring:
  config:
    activate:
      on-profile: test

---
