spring:
  artemis:
    mode: native
    user: ${ARTEMIS_MQ_USER:artemis}
    password: ${ARTEMIS_MQ_PASS:artemis}
    broker-url: ${BROKER_URL:tcp://localhost:61616}
  jms:
    pub-sub-domain: true

# defined by user
queue:
  main: mainQueue
  status: statusQueue
