spring:
  artemis:
    mode: native
    host: ${ACTIVE_MQ_HOST:localhost}
    port: ${ACTIVE_MQ_PORT:61616}
    user: ${ACTIVE_MQ_USER:artemis}
    password: ${ACTIVE_MQ_PASS:artemis}
  jms:
    pub-sub-domain: true

# defined by user
destination:
  main-queue: mainQueue
  status-queue: statusQueue

---
spring:
  config:
    activate:
      on-profile: embedded-artemis
  artemis:
    mode: embedded
    embedded:
      enabled: true
      queues: mainQueue,statusQueue
    host: localhost
    port: 61616

---
spring:
  config:
    activate:
      on-profile: test

---
