server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    zipkin:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
