name: dev-env
services:
  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis
    hostname: artemis
    restart: always
    ports:
      - "6161:61616"
      - "8161:8161"
  application:
    image: samanalishiri/application:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    hostname: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      ACTIVE_MQ_USER: artemis
      ACTIVE_MQ_PASS: artemis
      ACTIVE_MQ_HOST: localhost
      ACTIVE_MQ_PORT: 6161
