name: dev
services:
  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis
    hostname: artemis
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
  application:
    image: samanalishiri/application:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    hostname: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_PROFILES: artemis
      ACTIVE_MQ_USER: artemis
      ACTIVE_MQ_PASS: artemis
      BROKER_URL: tcp://artemis:61616
    depends_on:
      - artemis
