apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-credentials
  namespace: dev
type: Opaque
data:
  ARTEMIS_MQ_USER: YXJ0ZW1pcw==  # base64 encoded 'artemis'
  ARTEMIS_MQ_PASS: YXJ0ZW1pcw==  # base64 encoded 'artemis'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  APP_PROFILES: "artemis"
  BROKER_URL: "tcp://artemis:61616"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  namespace: dev
  labels:
    app: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
        - name: artemis
          image: apache/activemq-artemis:latest
          ports:
            - containerPort: 61616
            - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  namespace: dev
spec:
  selector:
    app: artemis
  ports:
    - name: queue-port
      port: 61616
      targetPort: 61616
    - name: management-ui-port
      port: 8161
      targetPort: 8161
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: samanalishiri/application:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dev-config
            - secretRef:
                name: dev-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: dev
spec:
  selector:
    app: application
  ports:
    - port: 8080
      targetPort: 8080
