apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: samanalishiri/application:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8080"
            - name: APP_PROFILES
              value: mysql,kafka,embedded-debezium
            - name: DATABASE_USERNAME
              value: user
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: tutorial_db
            - name: KAFKA_TOPIC_NAME
              value: cdc.tutorial_db.example_table
            - name: KAFKA_GROUP_ID
              value: cdc.tutorial_db.main-group
            - name: KAFKA_URL
              value: "kafka-service:9093"
            - name: TOPIC_PREFIX
              value: cdc
            - name: TABLES
              value: tutorial_db.example_table

---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
    - port: 8080
      targetPort: 8080
