spring:
  config:
    activate:
      on-profile: embedded-kafka
  kafka:
    topic:
      name: cdc.test_db.embedded-topic
    consumer:
      group-id: cdc.test_db.embedded-group
    bootstrap-servers: ${KAFKA_URL:localhost:9094}
