spring:
  kafka:
    topic:
      name: ${KAFKA_TOPIC_NAME:cdc.test_db.sample_table}
    consumer:
      group-id: ${KAFKA_GROUP_ID:cdc.test_db.main-group}
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
