spring:
  kafka:
    topic:
      name: tutorial.${KAFKA_TOPIC_NAME:test_db.sample_table}
    consumer:
      group-id: tutorial.${KAFKA_GROUP_ID:main-group}
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
