CREATE USER IF NOT EXISTS 'user' IDENTIFIED BY 'password';
GRANT SUPER, REPLICATION CLIENT ON *.* TO 'user'@'%';
GRANT REPLICATION SLAVE ON *.* TO 'user'@'%';
GRANT ALL ON `test_db`.* TO 'user'@'%';
FLUSH PRIVILEGES;
