name: dev-env
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      ELASTIC_PASSWORD: password
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    hostname: logstash
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: logstash_system
      ELASTICSEARCH_PASSWORD: password
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - "./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      elasticsearch:
        condition: service_healthy
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: password
    ports:
      - "5601:5601"
    volumes:
      - "./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      elasticsearch:
        condition: service_healthy
  application:
    image: samanalishiri/application:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: application
    hostname: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_PROFILES: default
      TCP_LOGGER_HOST: logstash
      TCP_LOGGER_PORT: 5044
      TCP_LOGGER_RECONNECT_DELAY: 5000
    depends_on:
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy
