name: dev
services:
  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo
    container_name: tempo
    hostname: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200" # Tempo
      - "4317:4317" # grpc
      - "4318:4318" # http
      - "9411:9411" # zipkin
  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    hostname: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    hostname: pyroscope
    ports:
      - '4040:4040'
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  application:
    image: samanalishiri/application:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    hostname: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_PROFILES: grafana
      TRACE_URL: http://tempo:4318/v1/traces
      METRICS_URL: http://tempo:4318/v1/metrics
      LOKI_URL: http://loki:3100/loki/api/v1/push
    depends_on:
      - loki
