server:
  address: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
spring:
  main:
    banner-mode: OFF
  profiles:
    active: ${APP_PROFILES:h2}
  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTHORIZATION_SERVER:http://localhost:8080}
      resourceserver:
        jwt:
          jwk-set-uri: ${RESOURCE_SERVER:http://localhost:8080}/oauth2/jwks
          issuer-uri: ${RESOURCE_SERVER:http://localhost:8080}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem


