version: '3.8'

services:
  artemis:
    image: apache/activemq-artemis
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: artemis
    hostname: artemis
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - "./broker:/opt/broker"

