version: '3.8'

services:
  artemis:
    image: apache/activemq-artemis
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: artemis
    hostname: artemis
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
#    volumes:
##     "-~/your local host path: exported volumes in docker file"
#      - ~/docker:/opt/broker
#      - ~/docker:/opt/artemis

