server:
  address: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
spring:
  application:
    name: observability-jaeger
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACING_HOST:http://localhost:4318/v1/traces}
---
spring:
  config:
    activate:
      on-profile: test
management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces