apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle
        image: container-registry.oracle.com/database/express:21.3.0-xe
        ports:
        - containerPort: 1521
        - containerPort: 5500
        env:
        - name: ORACLE_PWD
          value: password
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: oracle-data
      volumes:
      - name: oracle-data
        persistentVolumeClaim:
          claimName: ords-config-pvc
