apiVersion: apps/v1
kind: Deployment
metadata:
  name: ords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ords
  template:
    metadata:
      labels:
        app: ords
    spec:
      containers:
        - name: ords
          image: container-registry.oracle.com/database/ords:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/ords/config
              name: ords-config
          command: [ "ords", "serve" ]
      volumes:
        - name: ords-config
          persistentVolumeClaim:
            claimName: ords-config-pvc
