apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium
          image: debezium/connect:3.0.0.Final
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8083
          env:
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: debezium-config
            - name: OFFSET_STORAGE_TOPIC
              value: debezium-offset
            - name: STATUS_STORAGE_TOPIC
              value: debezium-status
            - name: BOOTSTRAP_SERVERS
              value: "kafka-service:9093"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium
spec:
  selector:
    app: debezium
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debeziumui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debeziumui
  template:
    metadata:
      labels:
        app: debeziumui
    spec:
      containers:
        - name: debeziumui
          image: debezium/debezium-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CONNECT_URIS
              value: http://debezium:8083
---
apiVersion: v1
kind: Service
metadata:
  name: debeziumui
spec:
  selector:
    app: debeziumui
  ports:
    - port: 8082
      targetPort: 8080