apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_CFG_LISTENERS
              value: "LOCALHOST://:9092,CONTAINER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "LOCALHOST://localhost:9092,CONTAINER://kafka-service:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "LOCALHOST:PLAINTEXT,CONTAINER:PLAINTEXT"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "LOCALHOST"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
      volumes:
        - name: kafka-data
          emptyDir: { }