version: "3.8"

services:
  postgresql:
    image: postgres:13.9-alpine
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
  securityrbac:
    image: samanalishiri/securityrbac:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: securityrbac
    hostname: securityrbac
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      DATABASE_NAME: test_db
