server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
spring:
  main:
    banner-mode: OFF
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:rdbms_h2;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
  h2:
    console:
      enabled: true
      path: "/h2-console"

