version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
  securityoauth2client:
    image: samanalishiri/securityoauth2client:latest
    build:
      context: security-oauth2-client
      dockerfile: /Dockerfile
    container_name: securityoauth2client
    hostname: securityoauth2client
    restart: always
    ports:
      - "8081:8081"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8081"
      APP_PROFILES: h2
      AUTHORIZATION_SERVER: "http://securityoauth2server.localhost"
      RESOURCE_SERVER: "http://securityoauth2server:8080"
      CLIENT_APP: "http://securityoauth2client.localhost"
  securityoauth2server:
    image: samanalishiri/securityoauth2server:latest
    build:
      context: security-oauth2-server
      dockerfile: /Dockerfile
    container_name: securityoauth2server
    hostname: securityoauth2server
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_PROFILES: h2,openapibasic
      AUTHORIZATION_SERVER: "http://securityoauth2server.localhost"
      RESOURCE_SERVER: "http://securityoauth2server:8080"
