apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: queue-port
      port: 5672
      targetPort: 5672
    - name: management-ui-port
      port: 15672
      targetPort: 15672
