apiVersion: v1
kind: Service
metadata:
  name: mysql-workbench
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: mysql-workbench
