apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  # value: root
  mysql-root-password: cm9vdA==
  # value: user
  mysql-user: dXNlcg==
  # value: password
  mysql-password: cGFzc3dvcmQ=