apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-workbench
  labels:
    app: mysql-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-workbench
  template:
    metadata:
      labels:
        app: mysql-workbench
    spec:
      containers:
        - name: mysql-workbench
          image: lscr.io/linuxserver/mysql-workbench:latest
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
