apiVersion: v1
kind: Service
metadata:
  name: mysql-workbench
spec:
  selector:
    app: mysql-workbench
  ports:
    - name: http-port
      port: 3000
      targetPort: 3000
    - name: https-port
      port: 3001
      targetPort: 3001
