spring:
  application:
    name: observability-grafana-stack
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_ZIPKIN:http://localhost:9411/api/v2/spans}
    metrics:
      export:
        url: ${TEMPO_HTTP:http://localhost:4318/v1/metrics}