spring:
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACE_URL:http://localhost:4318/v1/traces}
#    metrics:
#      export:
#        url: ${METRICS_URL:http://localhost:4318/v1/metrics}
#  zipkin:
#    tracing:
#      endpoint: ${TEMPO_ZIPKIN:http://localhost:9411/api/v2/spans}

# Added by developer
LOKI_URL: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}