spring:
  datasource:
    username: ${DATABASE_USERNAME:system}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${DATABASE_NAME:xepdb1}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.OracleDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        generate_statistics: true
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_schema: ${spring.datasource.username}
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create