version: "3.8"

services:
  restfulwebapi:
    image: samanalishiri/restfulwebapi:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: restfulwebapi
    hostname: restfulwebapi
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
