version: "3.8"

services:
  restful-web-api:
    image: samanalishiri/restful-web-services:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: restful-web-api
    hostname: restful-web-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
