apiVersion: apps/v1
kind: Deployment
metadata:
  name: securityrbacjwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securityrbacjwt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: securityrbacjwt
    spec:
      containers:
        - name: securityrbacjwt
          image: samanalishiri/securityrbacjwt:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8080"
            - name: APP_PROFILES
              value: postgres,openapibasic
            - name: DATABASE_USERNAME
              value: user
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: test_db
            - name: DATABASE_SCHEMA
              value: user_management
