apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-credentials
  namespace: dev
type: Opaque
data:
  # value: root
  MYSQL_ROOT_PASSWORD: cm9vdA==
  # value: user
  MYSQL_USER: dXNlcg==
  # value: password
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  # application
  # value: user
  APP_DATABASE_USERNAME: dXNlcg==
  # value: password
  APP_DATABASE_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev
data:
  # Database
  MYSQL_DATABASE: "tutorial_db"
  # Application
  APP_DATABASE_HOST: mysql
  APP_DATABASE_PORT: '3306'
  APP_DATABASE_NAME: tutorial_db
  APP_HOST: 0.0.0.0
  APP_PORT: '8080'
  APP_PROFILES: "mysql"
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"
  PMA_ARBITRARY: "1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: dev-config
            - secretRef:
                name: dev-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-workbench
  namespace: dev
  labels:
    app: mysql-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-workbench
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-workbench
    spec:
      containers:
        - name: mysql-workbench
          image: lscr.io/linuxserver/mysql-workbench:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: dev-config
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-workbench
  namespace: dev
  labels:
    app: mysql-workbench
spec:
  selector:
    app: mysql-workbench
  ports:
    - name: workbench-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: workbench-3001
      protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: dev
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: dev
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - name: adminer
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: dev
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: dev
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: samanalishiri/application:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dev-config
            - secretRef:
                name: dev-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: dev
spec:
  selector:
    app: application
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080 