server:
  address: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
  servlet:
    context-path: /securityoauth2client
spring:
  main:
    banner-mode: OFF
  profiles:
    active: ${APP_PROFILES:h2}

#  address: client-app.local
local:
  oauth2:
    server-url: ${OAUTH2_SERVER:http://securityoauth2server:8080/securityoauth2server}
    app-url: ${PROTOCOL:http}://${server.address}:${server.port}${server.servlet.context-path}