server:
  address: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8081}
spring:
  main:
    banner-mode: OFF
  profiles:
    active: ${APP_PROFILES:h2}

local:
  oauth2:
    authorizationserver: ${AUTHORIZATION_SERVER:http://securityoauth2server.localhost}
    resourceserver: ${RESOURCE_SERVER:http://securityoauth2server:8080}
    clientapp: ${CLIENT_APP:http://securityoauth2client.localhost}