apiVersion: v1
kind: Service
metadata:
  name: artemis
spec:
  selector:
    app: artemis
  ports:
    - name: queue-port
      port: 6161
      targetPort: 6161
    - name: management-ui-port
      port: 8161
      targetPort: 8161
