name: Spring Boot Tutorial

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - name: Install Docker
#        run: |
#            sudo apt-get update
#            sudo apt-get install -y docker.io
#            sudo systemctl start docker
#            sudo systemctl enable docker

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn -f hello-world/pom.xml clean package -DskipTests=true

      - name: Run tests with Maven
        run: |
          mvn -f hello-world/pom.xml clean test


